version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:16.15.0
    working_directory: ~/project
  mac_ios:
    macos:
      xcode: '14.1'
    environment:
      FL_OUTPUT_DIR: output
    working_directory: ~/project
  mac_android:
    docker:
      - image: circleci/android:api-29-node
    working_directory: ~/project

commands:
  attach_project:
    steps:
      - attach_workspace:
          at: ~/project
  config_dependencies:
    steps:
      - run: brew install xcodegen

jobs:
  install-dependencies:
    executor: mac_ios
    steps:
      - checkout
      - attach_project
      - config_dependencies
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Install dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .

  lint:
    executor: mac_ios
    steps:
      - attach_project
      - run:
          name: Lint files
          command: |
            yarn lint

  unit-tests:
    executor: mac_ios
    steps:
      - attach_project
      - run:
          name: Run unit tests
          command: |
            yarn test:ci
      - store_artifacts:
          path: coverage
          destination: coverage

  build-iOS:
    executor: mac_ios
    steps:
      - checkout
      - attach_project

      - run:
          command: |
            yarn ios

      - run:
          command: |
            bundle install
          working_directory: ios
      - store_artifacts:
          path: output
          destination: output

  build-android:
    executor: mac_android
    steps:
      - checkout
      - attach_project

      - run:
          command: |
            yarn ios

      - run:
          command: |
            bundle install
          working_directory: android

workflows:
  build-and-test:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - unit-tests:
          requires:
            - install-dependencies
      - build-iOS:
          requires:
            - install-dependencies
            - lint
            - unit-tests
            # - node
      - build-android:
          requires:
            - install-dependencies
            - lint
            - unit-tests
            # - node
