name: rnclean

option:
  minimumXcodeGenVersion: 2.29
  generateEmptyDirectories: YES
  depolymentTarget:
    iOS: 13.0
    watchOS: 6.0
  defaultConfigurations:
    debug: Debug
    release: Release

settings:
  configs:
    Debug:
      COPY_PHASE_STRIP: NO
      MTL_ENABLE_DEBUG_INFO: YES
    Release:
      COPY_PHASE_STRIP: YES
      MTL_ENABLE_DEBUG_INFO: NO

targets:
  rnclean:
    type: application
    platform: iOS

    sources:
      - rnclean

    settings:
      base:
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        PRODUCT_BUNDLE_IDENTIFIER: com.rnclean
        PRODUCT_NAME: rnclean
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: $(TARGET_NAME)
        CLANG_ENABLE_MODULES: YES
        OTHER_LDFLAGS:
          - $(inherited)
          - -ObjC
          - -lc++
      INFOPLIST_FILE: rnclean/Info.plist
      OTHER_SWIFT_FLAGS:
        Debug:
          - $(inherited)
          - -D COCOAPODS -Xcc -fmodule-map-file="${PODS_CONFIGURATION_BUILD_DIR}/YogaKit/YogaKit.modulemap" -Xcc -fmodule-map-file="${PODS_ROOT}/Headers/Private/yoga/Yoga.modulemap" -Xcc -fmodule-map-file="${PODS_ROOT}/Headers/Public/FlipperKit/FlipperKit.modulemap" -Xcc -fmodule-map-file="${PODS_ROOT}/Headers/Public/RCTTypeSafety/RCTTypeSafety.modulemap" -Xcc -fmodule-map-file="${PODS_ROOT}/Headers/Public/React/React-Core.modulemap" -Xcc -fmodule-map-file="${PODS_ROOT}/Headers/Public/ReactCommon/ReactCommon.modulemap" -Xcc -fmodule-map-file="${PODS_ROOT}/Headers/Public/React_Codegen/React-Codegen.modulemap" -Xcc -fmodule-map-file="${PODS_ROOT}/Headers/Public/folly/RCT-Folly.modulemap" -Xcc -DFB_SONARKIT_ENABLED=1
        Release:
          - $(inherited)
          - -D COCOAPODS -Xcc -fmodule-map-file="${PODS_CONFIGURATION_BUILD_DIR}/YogaKit/YogaKit.modulemap" -Xcc -fmodule-map-file="${PODS_ROOT}/Headers/Private/yoga/Yoga.modulemap" -Xcc -fmodule-map-file="${PODS_ROOT}/Headers/Public/RCTTypeSafety/RCTTypeSafety.modulemap" -Xcc -fmodule-map-file="${PODS_ROOT}/Headers/Public/React/React-Core.modulemap" -Xcc -fmodule-map-file="${PODS_ROOT}/Headers/Public/ReactCommon/ReactCommon.modulemap" -Xcc -fmodule-map-file="${PODS_ROOT}/Headers/Public/React_Codegen/React-Codegen.modulemap" -Xcc -fmodule-map-file="${PODS_ROOT}/Headers/Public/folly/RCT-Folly.modulemap"
      PODS_BUILD_DIR: ${BUILD_DIR}
      PODS_CONFIGURATION_BUILD_DIR:
        Debug: ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
        Release: ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
      PODS_PODFILE_DIR_PATH: ${SRCROOT}/.
      PODS_ROOT: ${SRCROOT}/Pods
      PODS_XCFRAMEWORKS_BUILD_DIR: $(PODS_CONFIGURATION_BUILD_DIR)/XCFrameworkIntermediates
      REACT_NATIVE_PATH: ${PODS_ROOT}/../../node_modules/react-native
      SWIFT_INCLUDE_PATHS:
        - $(inherited)
        - '${PODS_CONFIGURATION_BUILD_DIR}/YogaKit'
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      SWIFT_VERSION: 5.0
      USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES: YES

    configs:
      Debug:
        ENABLE_BITCODE: NO
        GCC_PREPROCESSOR_DEFINITIONS:
          - $(inherited)
          - FB_SONARKIT_ENABLED=1

    preBuildScripts:
      - name: Start Packager
        script: |
          export RCT_METRO_PORT="${RCT_METRO_PORT:=8081}"
          echo "export RCT_METRO_PORT=${RCT_METRO_PORT}" > "${SRCROOT}/../node_modules/react-native/scripts/.packager.env"
          if [ -z "${RCT_NO_LAUNCH_PACKAGER+xxx}" ] ; then
            if nc -w 5 -z localhost ${RCT_METRO_PORT} ; then
              if ! curl -s "http://localhost:${RCT_METRO_PORT}/status" | grep -q "packager-status:running" ; then
                echo "Port ${RCT_METRO_PORT} already in use, packager is either not running or not running correctly"
                exit 2
              fi
            else
              open "$SRCROOT/../node_modules/react-native/scripts/launchPackager.command" || echo "Can't start packager automatically"
            fi
          fi
        showEnvVars: NO

    postBuildScripts:
      - name: Bundle React Native code and images
        script: |
          set -e

          WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
          REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"

          /bin/sh -c "$WITH_ENVIRONMENT $REACT_NATIVE_XCODE"
